project_id = "zjmxvunmokqjzexvqrla"

[functions.invite-team-member]
verify_jwt = true

[functions.manage-team-member]
verify_jwt = true

[functions.verify-store-purchase]
verify_jwt = true

[functions.store-server-notification]
verify_jwt = false
