name: qudrat_maghrabi_app
description: "تطبيق قدرات المغربي للطلاب وأولياء الأمور."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.6.0
  supabase_flutter: 2.16.0
  url_launcher: 6.3.2
  webview_flutter: 4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/brand/

  fonts:
    - family: FrutigerArabic
      fonts:
        - asset: assets/fonts/FrutigerLTArabic45Light.ttf
          weight: 300
        - asset: assets/fonts/FrutigerLTArabic55Roman.ttf
          weight: 400
        - asset: assets/fonts/FrutigerLTArabic65Bold.ttf
          weight: 700
        - asset: assets/fonts/FrutigerLTArabic75Black.ttf
          weight: 900
